---
- hosts: audit
 gather_facts: no
 become: yes
 tasks:
   - name: AUDIT FRR
     service: name=frr state=stopped
     notify:
     - launch a ticket
 handlers:
   - name: launch a ticket
     debug: msg="Launching a ticket"
